apiVersion: apps/v1
kind: Deployment

metadata:
  name: afterlearning

spec:
  replicas: 1
  selector:
    matchLabels:
      app: afterlearning

  template:
    metadata:
      labels:
        app: afterlearning
    spec:
      containers:
        - name: afterlearning
          image: sirajahmad77/afterlearning:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
