apiVersion: apps/v1
kind: Deployment
metadata:
  name: afterlearning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afterlearning
  template:
    metadata:
      labels:
        app: afterlearning
    spec:
      containers:
      - name: afterlearning
        image: sirajahmad77/afterlearning:17  # Hardcoded latest build number
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
